# Generated by Django 4.2.2 on 2023-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('suite', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('phone', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('catchPhrase', models.CharField(max_length=100)),
                ('bs', models.CharField(max_length=100)),
            ],
        ),
    ]
