# Generated by Django 4.2.2 on 2023-06-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uit_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UITUser',
        ),
    ]
